version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/lemonapi:ro
    tty: true
    depends_on:
      - redis
      - postgres

    ports:
      - "127.0.0.1:5001:5001"

  redis:
    image: "redis:latest"  

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: api
      POSTGRES_PASSWORD: lemonapi
      POSTGRES_USER: apiuser
